version: '3'
services:
  api:
    image: node:16.15.0
    container_name: dev_api
    ports: 
      - 3000:3000
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    environment: 
      - PGUSER=romeo
      - PGHOST=db
      - PGPASSWORD=jkljkl
      - PGDATABASE=shelter_dev
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    image: postgres:14.5
    container_name: dev_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=shelter_dev
      - POSTGRES_USER=romeo
      - POSTGRES_PASSWORD=jkljkl
      
volumes:
  dbdata:
networks: 
  default:
    name: app_dev
