version: '3'
services:
  api:
    image: node:16.15.0
    container_name: test_api
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    environment: 
      - PGUSER=romeo
      - PGHOST=db
      - PGPASSWORD=jkljkl
      - PGDATABASE=shelter_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14.5
    container_name: test_db
    volumes:
      - test_db:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d/:ro
    environment: 
      - POSTGRES_USER=romeo
      - POSTGRES_DB=shelter_test
      - POSTGRES_PASSWORD=jkljkl
      
volumes:
  test_db:
networks: 
  default:
    name: app_test
